/* Carte del Taboo del Mare: parola da far indovinare (w) e cinque parole vietate (t).
   Le usa anche «Salva la tartaruga», che mostra le parole vietate come indizi. */
'use strict';
window.TABOO_CARDS = [
  // Vita marina
  { w: 'SPIAGGIA', t: ['Sabbia', 'Mare', 'Ombrellone', 'Estate', 'Bagno'] },
  { w: 'TARTARUGA', t: ['Guscio', 'Carapace', 'Lenta', 'Rettile', 'Uova'] },
  { w: 'MEDUSA', t: ['Tentacoli', 'Pungere', 'Urticante', 'Trasparente', 'Gelatina'] },
  { w: 'DELFINO', t: ['Mammifero', 'Salto', 'Intelligente', 'Pinna', 'Flipper'] },
  { w: 'BALENA', t: ['Enorme', 'Cetaceo', 'Mammifero', 'Moby Dick', 'Sfiatatoio'] },
  { w: 'CAPODOGLIO', t: ['Balena', 'Testa', 'Cetaceo', 'Grande', 'Immersione'] },
  { w: 'SQUALO', t: ['Denti', 'Pinna', 'Predatore', 'Pericoloso', 'Film'] },
  { w: 'POLPO', t: ['Tentacoli', 'Otto', 'Inchiostro', 'Ventose', 'Mollusco'] },
  { w: 'GRANCHIO', t: ['Chele', 'Laterale', 'Crostaceo', 'Pinze', 'Scoglio'] },
  { w: 'STELLA MARINA', t: ['Cinque', 'Braccia', 'Punte', 'Cielo', 'Fondale'] },
  { w: 'CAVALLUCCIO MARINO', t: ['Pesce', 'Coda', 'Maschio', 'Muso', 'Piccolo'] },
  { w: 'PESCE PALLA', t: ['Gonfiarsi', 'Spine', 'Veleno', 'Rotondo', 'Giappone'] },
  { w: 'PESCE SPADA', t: ['Naso', 'Lungo', 'Sicilia', 'Punta', 'Arma'] },
  { w: 'RICCIO DI MARE', t: ['Spine', 'Pungere', 'Scoglio', 'Nero', 'Mangiare'] },
  { w: 'FOCA', t: ['Pinne', 'Polo', 'Baffi', 'Ghiaccio', 'Circo'] },
  { w: 'CORALLO', t: ['Rosso', 'Barriera', 'Collana', 'Colonia', 'Tropicale'] },
  { w: 'BARRIERA CORALLINA', t: ['Australia', 'Colori', 'Tropicale', 'Pesci', 'Sbiancamento'] },
  { w: 'POSIDONIA', t: ['Pianta', 'Alga', 'Prateria', 'Foglie', 'Mediterraneo'] },
  { w: 'ALGA', t: ['Verde', 'Pianta', 'Viscida', 'Sushi', 'Scoglio'] },
  { w: 'PLANCTON', t: ['Microscopico', 'Piccolissimo', 'Cibo', 'Balena', 'Galleggiare'] },
  { w: 'TONNO', t: ['Scatoletta', 'Pesce', 'Rosso', 'Sushi', 'Olio'] },
  { w: 'BANCO DI PESCI', t: ['Gruppo', 'Insieme', 'Nuotare', 'Sardine', 'Tanti'] },
  { w: 'GABBIANO', t: ['Uccello', 'Bianco', 'Volare', 'Porto', 'Mare'] },
  { w: 'FENICOTTERO', t: ['Rosa', 'Zampa', 'Uccello', 'Collo', 'Lago'] },
  { w: 'CONCHIGLIA', t: ['Spiaggia', 'Guscio', 'Mollusco', 'Orecchio', 'Raccogliere'] },
  { w: 'ACQUARIO', t: ['Vasca', 'Pesci', 'Vetro', 'Genova', 'Rossi'] },

  // Mare e costa
  { w: 'SCOGLIO', t: ['Roccia', 'Tuffarsi', 'Pietra', 'Riva', 'Onde'] },
  { w: 'SABBIA', t: ['Spiaggia', 'Granelli', 'Deserto', 'Castello', 'Clessidra'] },
  { w: 'ONDA', t: ['Mare', 'Surf', 'Cresta', 'Tsunami', 'Schiuma'] },
  { w: 'MAREA', t: ['Luna', 'Alta', 'Bassa', 'Livello', 'Oceano'] },
  { w: 'CORRENTE', t: ['Elettrica', 'Flusso', 'Trascinare', 'Fiume', 'Direzione'] },
  { w: 'OCEANO', t: ['Atlantico', 'Pacifico', 'Mare', 'Grande', 'Continente'] },
  { w: 'MAR MEDITERRANEO', t: ['Italia', 'Grecia', 'Nostrum', 'Gibilterra', 'Africa'] },
  { w: 'ISOLA', t: ['Terra', 'Circondata', 'Arcipelago', 'Naufrago', 'Sicilia'] },
  { w: 'LAGUNA', t: ['Venezia', 'Lago', 'Salmastra', 'Gondola', 'Acqua'] },
  { w: 'FIUME', t: ['Acqua', 'Po', 'Tevere', 'Sfociare', 'Ponte'] },
  { w: 'FOCE', t: ['Fiume', 'Delta', 'Sbocco', 'Sfociare', 'Estuario'] },
  { w: 'SALINA', t: ['Sale', 'Trapani', 'Evaporare', 'Fenicotteri', 'Vasche'] },
  { w: 'SALE', t: ['Marino', 'Sapore', 'Cucina', 'Pepe', 'Zucchero'] },
  { w: 'SOLE', t: ['Caldo', 'Luce', 'Stella', 'Giorno', 'Estate'] },
  { w: 'FARO', t: ['Luce', 'Torre', 'Navi', 'Notte', 'Costa'] },
  { w: 'PORTO', t: ['Navi', 'Molo', 'Banchina', 'Attraccare', 'Barche'] },
  { w: 'AREA MARINA PROTETTA', t: ['Riserva', 'Parco', 'Vietato', 'Pesca', 'Tutela'] },

  // Gente di mare
  { w: 'BARCA A VELA', t: ['Vento', 'Regata', 'Albero', 'Timone', 'Navigare'] },
  { w: 'SCIALUPPA', t: ['Salvataggio', 'Nave', 'Titanic', 'Piccola', 'Remi'] },
  { w: 'NAVE DA CROCIERA', t: ['Turisti', 'Vacanza', 'Enorme', 'Cabina', 'Porto'] },
  { w: 'PESCATORE', t: ['Pesce', 'Barca', 'Canna', 'Amo', 'Rete'] },
  { w: 'RETE DA PESCA', t: ['Maglie', 'Strascico', 'Barca', 'Intrappolare', 'Tonno'] },
  { w: 'LUPO DI MARE', t: ['Marinaio', 'Esperto', 'Vecchio', 'Barba', 'Navigare'] },
  { w: 'NAUFRAGO', t: ['Isola', 'Deserta', 'Robinson Crusoe', 'Nave', 'Affondare'] },
  { w: 'SUBACQUEO', t: ['Immersione', 'Bombola', 'Sott’acqua', 'Muta', 'Sub'] },
  { w: 'BOMBOLA', t: ['Ossigeno', 'Aria', 'Gas', 'Sub', 'Respirare'] },
  { w: 'PINNE', t: ['Nuotare', 'Piedi', 'Sub', 'Pesce', 'Squalo'] },
  { w: 'MASCHERA', t: ['Carnevale', 'Viso', 'Occhi', 'Boccaglio', 'Sub'] },
  { w: 'BAGNINO', t: ['Salvataggio', 'Spiaggia', 'Fischietto', 'Torretta', 'Baywatch'] },
  { w: 'OMBRELLONE', t: ['Spiaggia', 'Sole', 'Ombra', 'Lettino', 'Sdraio'] },
  { w: 'CREMA SOLARE', t: ['Sole', 'Pelle', 'Protezione', 'Scottatura', 'Spalmare'] },
  { w: 'SURF', t: ['Tavola', 'Onde', 'Cavalcare', 'California', 'Hawaii'] },
  { w: 'VOLONTARIO', t: ['Gratis', 'Aiutare', 'Associazione', 'Pagato', 'Tempo'] },
  { w: 'GUANTI', t: ['Mani', 'Indossare', 'Freddo', 'Dita', 'Lattice'] },

  // Plastica e rifiuti
  { w: 'PLASTICA', t: ['Bottiglia', 'Materiale', 'Petrolio', 'Riciclare', 'Sacchetto'] },
  { w: 'MICROPLASTICHE', t: ['Piccole', 'Frammenti', 'Particelle', 'Invisibili', 'Pezzetti'] },
  { w: 'SACCHETTO', t: ['Busta', 'Spesa', 'Supermercato', 'Plastica', 'Portare'] },
  { w: 'CANNUCCIA', t: ['Bere', 'Bibita', 'Succhiare', 'Tubo', 'Bicchiere'] },
  { w: 'BORRACCIA', t: ['Acqua', 'Bottiglia', 'Riutilizzabile', 'Bere', 'Metallo'] },
  { w: 'BOTTIGLIA', t: ['Acqua', 'Vetro', 'Tappo', 'Bere', 'Vino'] },
  { w: 'TAPPO', t: ['Bottiglia', 'Chiudere', 'Sughero', 'Vino', 'Svitare'] },
  { w: 'LATTINA', t: ['Alluminio', 'Bibita', 'Metallo', 'Aprire', 'Birra'] },
  { w: 'VETRO', t: ['Bottiglia', 'Trasparente', 'Rompere', 'Finestra', 'Campana'] },
  { w: 'POLISTIROLO', t: ['Bianco', 'Leggero', 'Imballaggio', 'Pallini', 'Cassetta'] },
  { w: 'IMBALLAGGIO', t: ['Pacco', 'Scatola', 'Confezione', 'Proteggere', 'Cartone'] },
  { w: 'PALLONCINO', t: ['Gonfiare', 'Festa', 'Elio', 'Aria', 'Scoppiare'] },
  { w: 'MOZZICONE', t: ['Sigaretta', 'Fumo', 'Cicca', 'Filtro', 'Posacenere'] },
  { w: 'SPAZZOLINO', t: ['Denti', 'Lavare', 'Dentifricio', 'Setole', 'Bocca'] },
  { w: 'USA E GETTA', t: ['Monouso', 'Una volta', 'Buttare', 'Piatti', 'Bicchieri'] },
  { w: 'RIUTILIZZABILE', t: ['Usare', 'Di nuovo', 'Più volte', 'Lavare', 'Durare'] },
  { w: 'BORSA DI TELA', t: ['Stoffa', 'Spesa', 'Sacchetto', 'Cotone', 'Riutilizzabile'] },
  { w: 'RICICLO', t: ['Rifiuti', 'Differenziata', 'Trasformare', 'Materiale', 'Riutilizzare'] },
  { w: 'RACCOLTA DIFFERENZIATA', t: ['Bidoni', 'Separare', 'Rifiuti', 'Colori', 'Carta'] },
  { w: 'RIFIUTO', t: ['Spazzatura', 'Immondizia', 'Buttare', 'Pattumiera', 'Cestino'] },
  { w: 'CESTINO', t: ['Spazzatura', 'Buttare', 'Carta', 'Pattumiera', 'Rifiuti'] },
  { w: 'DISCARICA', t: ['Rifiuti', 'Spazzatura', 'Camion', 'Puzza', 'Montagna'] },
  { w: 'COMPOST', t: ['Organico', 'Avanzi', 'Terra', 'Concime', 'Umido'] },
  { w: 'BIODEGRADABILE', t: ['Decomporsi', 'Naturale', 'Compostabile', 'Sparire', 'Tempo'] },
  { w: 'SPRECO ALIMENTARE', t: ['Cibo', 'Buttare', 'Avanzi', 'Frigo', 'Scadenza'] },
  { w: 'ACQUA DEL RUBINETTO', t: ['Lavandino', 'Bere', 'Casa', 'Bottiglia', 'Potabile'] },
  { w: 'ISOLA DI PLASTICA', t: ['Pacifico', 'Rifiuti', 'Galleggiare', 'Oceano', 'Enorme'] },

  // Ambiente e clima
  { w: 'INQUINAMENTO', t: ['Sporco', 'Smog', 'Rifiuti', 'Ambiente', 'Aria'] },
  { w: 'PETROLIO', t: ['Nero', 'Benzina', 'Pozzo', 'Estrarre', 'Barile'] },
  { w: 'MAREA NERA', t: ['Petrolio', 'Petroliera', 'Macchia', 'Disastro', 'Uccelli'] },
  { w: 'BIODIVERSITÀ', t: ['Specie', 'Varietà', 'Animali', 'Piante', 'Natura'] },
  { w: 'ECOSISTEMA', t: ['Ambiente', 'Habitat', 'Equilibrio', 'Specie', 'Natura'] },
  { w: 'ESTINZIONE', t: ['Sparire', 'Specie', 'Dinosauri', 'Rischio', 'Ultimi'] },
  { w: 'OSSIGENO', t: ['Respirare', 'Aria', 'Gas', 'Vita', 'Bombola'] },
  { w: 'CLIMA', t: ['Tempo', 'Meteo', 'Temperatura', 'Cambiamento', 'Caldo'] },
  { w: 'RISCALDAMENTO GLOBALE', t: ['Temperatura', 'Clima', 'Caldo', 'Pianeta', 'Aumento'] },
  { w: 'EFFETTO SERRA', t: ['Gas', 'CO₂', 'Atmosfera', 'Caldo', 'Clima'] },
  { w: 'GHIACCIAIO', t: ['Alpi', 'Montagna', 'Sciogliersi', 'Neve', 'Freddo'] },
  { w: 'ORSO POLARE', t: ['Bianco', 'Polo Nord', 'Ghiaccio', 'Artico', 'Foca'] },
  { w: 'PINGUINO', t: ['Antartide', 'Uccello', 'Bianco e nero', 'Freddo', 'Volare'] },
  { w: 'SICCITÀ', t: ['Pioggia', 'Acqua', 'Secco', 'Arido', 'Estate'] },
  { w: 'ALLUVIONE', t: ['Pioggia', 'Fiume', 'Acqua', 'Esondare', 'Fango'] },
  { w: 'PANNELLO SOLARE', t: ['Sole', 'Energia', 'Tetto', 'Elettricità', 'Fotovoltaico'] },
  { w: 'PALA EOLICA', t: ['Vento', 'Energia', 'Girare', 'Mulino', 'Turbina'] },
  { w: 'ENERGIA RINNOVABILE', t: ['Sole', 'Vento', 'Pulita', 'Fonti', 'Infinita'] },
  { w: 'CARBONE', t: ['Nero', 'Befana', 'Fossile', 'Bruciare', 'Miniera'] },
  { w: 'AUTO ELETTRICA', t: ['Batteria', 'Ricaricare', 'Colonnina', 'Benzina', 'Macchina'] },
  { w: 'BICICLETTA', t: ['Pedalare', 'Ruote', 'Sella', 'Catena', 'Bici'] },
  { w: 'ALBERO', t: ['Foglie', 'Radici', 'Tronco', 'Bosco', 'Rami'] },
  { w: 'DEFORESTAZIONE', t: ['Alberi', 'Tagliare', 'Amazzonia', 'Foresta', 'Legno'] },
  { w: 'SOSTENIBILITÀ', t: ['Ambiente', 'Futuro', 'Risorse', 'Generazioni', 'Equilibrio'] },
  { w: 'GRETA THUNBERG', t: ['Svezia', 'Sciopero', 'Fridays for Future', 'Ragazza', 'Clima'] }
];
